# Generated by Django 4.0.1 on 2022-01-24 15:36

import datetimeutc.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=500)),
                ('headshot', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=500)),
                ('release_date', datetimeutc.fields.DateTimeUTCField()),
                ('timestamp', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
            ],
        ),
    ]
