# Generated by Django 4.0.1 on 2022-01-25 22:45

import datetimeutc.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('upc', models.IntegerField()),
                ('in_stock', models.BooleanField(default=False)),
                ('timestamp', datetimeutc.fields.DateTimeUTCField(auto_now_add=True)),
            ],
        ),
    ]
