# Generated by Django 4.0.1 on 2022-01-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=500)),
                ('headshot', models.CharField(max_length=500)),
                ('website', models.CharField(max_length=500)),
                ('timestamp', models.CharField(max_length=200)),
            ],
        ),
    ]
