# Generated by Django 4.0.1 on 2022-01-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
